name: "Build Ubuntu"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    # - name: Install Clang
    #   uses: ./.github/actions/install-clang

    - name: make
      run: make
